### PR TITLE
Update build process

### PR DESCRIPTION
**Pull request by slavede**
This will fix issue #13. I changed name of the project in package.json so I could publish it and use it, because I don't have permission to publish to your NPM project.
Feel free to change name of the package again to yours and publish new version.

Build and publish would be now done more easily (set version in package.json before):
```
ng-packagr -p package.json
npm publish dist
```

### CODE REVIEW

**Comment by slavede** [comment]
@matsura build is failing because I upgraded build process to use ng-packagr which fixes mentioned issue. Can you please approve PR? Or event better, are you feeling ok to give me colaborator role on your project?

**Comment by matsura** [comment]
@slavede Sadly I had no time to fix the issues in the project. Can you change the name and the url to the original, then I'll merge the PR and publish on npm the fixes?

**Comment by slavede** [comment]
Done, you can build and published as mentioned above.

**Comment by Rajh** [comment]
@slavede Hi,

I tried your version "slavede-ng-dual-list-box": "1.1.5"
But it still doesn't work :
ERROR in ./src/$$_gendir/~/slavede-ng-dual-list-box/slavede-ng-dual-list-box.ngfactory.ts
Module not found: Error: Can't resolve 'slavede-ng-dual-list-box/src/models/index' in '...\src\$$_gendir\node_modules\slavede-ng-dual-list-box'
 @ ./src/$$_gendir/~/slavede-ng-dual-list-box/slavede-ng-dual-list-box.ngfactory.ts 7:0-132
 @ ./src/$$_gendir/app/models/model-list/model-list.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Pull request merged**
